---
# flags to control the bahviour of the role
windows_from_iso:     false
windows_ad_server:    false
windows_dns_server:   false

# python interpreter with the correct packages installed
#ansible_python_interpreter: /opt/homebrew/bin/python3

# variables initialized via environment variables
vcenter:
  host:                   "{{ lookup('env','vcenter_host') }}"
  user:                   "{{ lookup('env','vcenter_user') }}"
  pwd:                    "{{ lookup('env','vcenter_pwd') }}"
  vmname:                 "{{ lookup('env','vcenter_vmname') }}"
  folder:                 "{{ lookup('env','vcenter_folder') }}"
  datacenter:             "{{ lookup('env','vcenter_datacenter') }}"
  validate_certs:         "{{ lookup('env','vcenter_validate_certs') }}"
  iso_controller_type:    "{{ lookup('env','vcenter_iso_controller_type') }}"
  iso_controller_number:  "{{ lookup('env','vcenter_iso_controller_number') }}"
  iso_unit_number:        "{{ lookup('env','vcenter_iso_unit_number') }}"
network:
  subnet:                 "{{ lookup('env','network_subnet') }}"
  address:                "{{ lookup('env','network_address') }}"
  gateway:                "{{ lookup('env','network_gateway') }}"
  nameserver:             "{{ lookup('env','network_nameserver') }}"
  proxy:                  "{{ lookup('env','network_proxy') }}"
installer:
  product_key:            "{{ lookup('env','product_key') }}"
  hostname:               "{{ lookup('env','installer_hostname') }}"
  name:                   "{{ lookup('env','installer_username') }}"
  user:                   "{{ lookup('env','installer_user') }}"
  pwd:                    "{{ lookup('env','installer_pwd') }}"
  time:                   "{{ lookup('env','installer_time') }}"

# settings for active directory domain controller
ad:
  domain: vielab.local
  pwd: Vielab123!

# settings for DNS server and windows machine as client
dns:
  records_a:
  - { name: "dns",    ip: "10.51.71.46", zone: "{{ ad.domain }}" }
  - { name: "ubuntu", ip: "10.51.71.47", zone: "{{ ad.domain }}" }
  servers:
  - "144.254.71.184"
  - "171.70.168.183"
  - "64.104.123.144"
  - "10.51.71.46"

# ini module defaults
input_module_defaults:
  vmware_guest_info:
    hostname:               '{{ vcenter.host }}'
    username:               '{{ vcenter.user }}'
    password:               '{{ vcenter.pwd }}'
    validate_certs:         '{{ vcenter.validate_certs }}'
    name:                   '{{ vcenter.vmname }}'
    folder:                 '{{ vcenter.folder }}'
    datacenter:             '{{ vcenter.datacenter }}'
  vmware_guest:
    hostname:               '{{ vcenter.host }}'
    username:               '{{ vcenter.user }}'
    password:               '{{ vcenter.pwd }}'
    validate_certs:         '{{ vcenter.validate_certs }}'
    name:                   '{{ vcenter.vmname }}'
    folder:                 '{{ vcenter.folder }}'
    datacenter:             '{{ vcenter.datacenter }}'
  vcenter_vm_info:
    vcenter_hostname:       '{{ vcenter.host }}'
    vcenter_username:       '{{ vcenter.user }}'
    vcenter_password:       '{{ vcenter.pwd }}'
    vcenter_validate_certs: '{{ vcenter.validate_certs }}'
  vmware_guest_sendkey:
    hostname:               '{{ vcenter.host }}'
    username:               '{{ vcenter.user }}'
    password:               '{{ vcenter.pwd }}'
    validate_certs:         '{{ vcenter.validate_certs }}'
    name:                   '{{ vcenter.vmname }}'
    folder:                 '{{ vcenter.folder }}'
    datacenter:             '{{ vcenter.datacenter }}'