---
ubuntu_from_iso: true

ubuntu_timezone:    "Europe/Vienna"
ubuntu_hostname:    "{{ inventory_hostname }}"
ubuntu_ntp_server:  "{{ lookup('env','ANSIBLE_UBUNTU_NTP_SERVER') }}"
ubuntu_ftp_proxy:   "{{ lookup('env','ANSIBLE_UBUNTU_FTP_PROXY') }}"
ubuntu_http_proxy:  "{{ lookup('env','ANSIBLE_UBUNTU_HTTP_PROXY') }}"
ubuntu_https_proxy: "{{ lookup('env','ANSIBLE_UBUNTU_HTTPS_PROXY') }}"

# install from iso fields
#ansible_python_interpreter: /opt/homebrew/bin/python3

vcenter:
  host:                   "{{ lookup('env','vcenter_host') }}"
  user:                   "{{ lookup('env','vcenter_user') }}"
  pwd:                    "{{ lookup('env','vcenter_pwd') }}"
  vmname:                 "{{ lookup('env','vcenter_vmname') }}"
  folder:                 "{{ lookup('env','vcenter_folder') }}"
  datacenter:             "{{ lookup('env','vcenter_datacenter') }}"
  validate_certs:         "{{ lookup('env','vcenter_validate_certs') }}"
  iso_controller_type:    "{{ lookup('env','vcenter_iso_controller_type') }}"
  iso_controller_number:  "{{ lookup('env','vcenter_iso_controller_number') }}"
  iso_unit_number:        "{{ lookup('env','vcenter_iso_unit_number') }}"
network:
  subnet:                 "{{ lookup('env','network_subnet') }}"
  address:                "{{ lookup('env','network_address') }}"
  gateway:                "{{ lookup('env','network_gateway') }}"
  nameserver:             "{{ lookup('env','network_nameserver') }}"
  proxy:                  "{{ lookup('env','network_proxy') }}"
installer:
  hostname:               "{{ lookup('env','installer_hostname') }}"
  name:                   "{{ lookup('env','installer_name') }}"
  user:                   "{{ lookup('env','installer_user') }}"
  pwd:                    "{{ lookup('env','installer_pwd') }}"
  time:                   "{{ lookup('env','installer_time') }}"

# module defaults used in main playbook
input_module_defaults:
  vmware_guest_info:
    hostname:               '{{ vcenter.host }}'
    username:               '{{ vcenter.user }}'
    password:               '{{ vcenter.pwd }}'
    validate_certs:         '{{ vcenter.validate_certs }}'
    name:                   '{{ vcenter.vmname }}'
    folder:                 '{{ vcenter.folder }}'
    datacenter:             '{{ vcenter.datacenter }}'
  vmware_guest:
    hostname:               '{{ vcenter.host }}'
    username:               '{{ vcenter.user }}'
    password:               '{{ vcenter.pwd }}'
    validate_certs:         '{{ vcenter.validate_certs }}'
    name:                   '{{ vcenter.vmname }}'
    folder:                 '{{ vcenter.folder }}'
    datacenter:             '{{ vcenter.datacenter }}'
  vcenter_vm_info:
    vcenter_hostname:       '{{ vcenter.host }}'
    vcenter_username:       '{{ vcenter.user }}'
    vcenter_password:       '{{ vcenter.pwd }}'
    vcenter_validate_certs: '{{ vcenter.validate_certs }}'
  vmware_guest_sendkey:
    hostname:               '{{ vcenter.host }}'
    username:               '{{ vcenter.user }}'
    password:               '{{ vcenter.pwd }}'
    validate_certs:         '{{ vcenter.validate_certs }}'
    name:                   '{{ vcenter.vmname }}'
    folder:                 '{{ vcenter.folder }}'
    datacenter:             '{{ vcenter.datacenter }}'