---
# file: group_vars/windows_server
ansible_user:     "{{ lookup('env','TF_INSTALLER_USR') }}"
ansible_password: "{{ lookup('env','TF_INSTALLER_PWD') }}"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
ansible_port: 5986
