---
# file: group_vars/windows_server
ansible_user:     Administrator
ansible_password: "{{ lookup('env','TF_VAR_WINDOWS_PWD') }}"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
ansible_port: 5986
