- name: Install basic ubuntu packages
  tags: ubuntu_basic
  apt:
    pkg:
      - vim
      - wget
      - curl
      - nmap
      - traceroute
      - net-tools
      - unzip
    update_cache: true
    state: latest
  register: result